mode: Medical3DBraTsSeg

batch_size: 1
iters: 15000

train_dataset:
  type: BraTsDataset
  dataset_root: /opt/data/private/BairdWorkspace/data
  result_dir: /opt/data/private/BairdWorkspace/data
  transforms: 
    - type: RandomRotation3D
      degrees: 90
    - type: ResampleImage
      resample_size: [128,128,128]
    # - type: GammaTransform
    #   gamma_range: [0.5,2]
    #   p_per_sample: 0.2
    # - type: GaussianNoiseTransform
    #   noise_variance: [0,0.1]
    #   p_per_sample: 0.15
    # - type: SimulateLowResolutionTransform
    #   zoom_range: [0.5,1.0]
    #   per_channel: True
    #   p_per_channel: 0.5
    # - type: BrightnessMultiplicativeTransform
    #   multiplier_range: [0.75,1.25]
    #   p_per_sample: 0.15
    # - type: ContrastAugmentationTransform
    #   contrast_range: [0.75,1.25]
    #   p_per_sample: 0.15
  mode: train
  num_classes: 4

val_dataset:
  type: BraTsDataset
  dataset_root: /opt/data/private/BairdWorkspace/data
  result_dir: /opt/data/private/BairdWorkspace/data
  num_classes: 4
  transforms: []
  mode: val
  