_base_: "../_base_/lung_coronavirus.yml"


optimizer:
  type: sgd
  lr: 0.01
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: OneCycleLR

model:
  type: VNet
  elu: False
  in_channels: 1
  num_classes: 3
 

loss:
  types:
    - type: DiceLoss3D
  coef: [1]